"""
End-to-end pipeline tests for the Lockstep AI agent backend.
Runs two test scenarios:
  Test 1: Writing — happy path, bad path, and mediation
  Test 2: Code — happy path and bad path
"""

import asyncio
import time

from pipeline import run_scope_parsing, run_evaluation, run_mediation

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

SEP = "=" * 70


def section(title: str):
    print(f"\n{SEP}")
    print(f"  {title}")
    print(SEP)


def subsection(title: str):
    print(f"\n--- {title} ---")


# ---------------------------------------------------------------------------
# Test data
# ---------------------------------------------------------------------------

WRITING_DESCRIPTION = """
Write an 800-1000 word blog post about the benefits of solar energy for homeowners.
The article should cover three main topics: cost savings, environmental benefits, and energy independence.
Use a friendly, accessible tone suitable for a general audience.
Include at least 2 specific statistics or data points.
Structure the article with an introduction, three main sections (one per topic), and a conclusion.
"""

GOOD_WRITING_DELIVERABLE = """
# Why Every Homeowner Should Consider Going Solar

If you've been curious about solar panels but haven't quite taken the plunge, you're not alone. Millions of homeowners across the country are weighing up whether the upfront cost is really worth it. The short answer: for most families, it absolutely is. Solar energy isn't just a feel-good environmental choice anymore — it's a smart financial decision with real, measurable benefits. Here's a look at the three biggest reasons homeowners are making the switch.

## 1. Significant Cost Savings on Your Energy Bills

Let's start with the number that matters most to most people: your monthly electricity bill. The average American household spends around $1,500 per year on electricity, according to the U.S. Energy Information Administration. A properly sized solar system can offset 70–100% of that usage, depending on your location and roof orientation.

The savings don't stop there. Many states offer net metering programs, which allow you to sell excess electricity back to the grid. On a sunny summer weekend when your panels are producing more than you can use, your meter actually runs backward — and your utility company credits your account. Homeowners in sunny states like Arizona and California have reported electric bills as low as $10–15 per month after going solar.

Then there's the federal solar investment tax credit (ITC), which currently allows you to deduct 30% of your solar installation costs from your federal taxes. On a $20,000 system, that's a $6,000 tax reduction. Many states layer additional incentives on top of that. The payback period for most residential solar installations today is between 6 and 10 years, after which you're essentially generating free electricity for the remaining 15–20 years of the system's lifespan.

## 2. Real Environmental Benefits That Add Up

Beyond your wallet, solar energy has a meaningful impact on the environment — and the numbers are striking. A typical residential solar system offsets approximately 100,000 pounds of carbon dioxide over its lifetime, according to the U.S. Environmental Protection Agency. That's equivalent to planting over 2,500 trees or taking two cars off the road for a decade.

Unlike burning fossil fuels, solar panels generate electricity without releasing greenhouse gases, particulates, or other air pollutants. They operate silently, require no water to generate power (unlike coal or nuclear plants, which consume enormous amounts), and have a relatively small physical footprint on your property.

Solar panels also have a surprisingly low environmental cost over their full lifecycle. Studies show that a typical panel "pays back" the energy used to manufacture it within 1–4 years, after which it produces clean energy for another two decades or more. As the grid becomes greener, solar panels become even cleaner over time since they're no longer displacing fossil fuels that were partly generated by renewables.

If reducing your household's carbon footprint is a priority, few single investments come close to matching rooftop solar in terms of impact per dollar spent.

## 3. Energy Independence and Protection from Rising Rates

One of the most underrated benefits of solar is what it does for your sense of financial security. Electricity prices in the United States have risen an average of 2.2% per year over the past decade, according to EIA data — and in some regions, the increases have been far steeper. When you generate your own power, you're insulated from those rate hikes.

Pair your solar system with a home battery like the Tesla Powerwall or the Enphase IQ Battery, and you're protected against outages too. During grid disruptions — increasingly common due to extreme weather events — solar-plus-storage homeowners can keep the lights on, run their refrigerators, and charge essential devices while their neighbors are in the dark.

Energy independence also means less reliance on utility companies whose pricing is subject to regulatory changes, fuel price volatility, and infrastructure costs outside your control. With solar, you become, in a real sense, your own power company. You decide when to use stored energy, when to draw from the grid, and — in some markets — when to sell back at peak pricing.

## Conclusion

Solar energy has crossed the threshold from niche technology to mainstream home improvement. The combination of falling installation costs, generous tax incentives, rising electricity rates, and maturing battery storage options means the math works for more homeowners than ever before. Whether you're primarily motivated by cutting your bills, shrinking your carbon footprint, or simply gaining more control over your home's energy future, solar delivers on all three fronts. The best time to go solar was five years ago; the second best time is today.
"""

BAD_WRITING_DELIVERABLE = """
# Solar Energy Can Save You Money

Solar panels are a great investment for homeowners. When you install solar panels on your roof, you can save a lot on your electricity bills. The sun provides free energy and solar panels convert that energy into electricity for your home.

Cost savings are the main benefit. Many people report lower bills after going solar. The government also offers tax credits which can reduce the cost of installation. Overall, solar panels tend to pay for themselves over time, though the exact timeline varies by location and usage.

Solar energy is also clean and renewable. Unlike coal or gas, the sun won't run out. This makes solar a sustainable choice for the future.

Going solar is a good decision for many homeowners who want to reduce costs and help the environment.
"""

CODE_DESCRIPTION = """
Build a Python function called `calculate_compound_interest` that takes principal, annual_rate, years, and compounds_per_year as arguments and returns the final amount.
Include type hints.
Include a docstring explaining the function.
Include at least 3 unit tests using pytest.
"""

GOOD_CODE_DELIVERABLE = '''
def calculate_compound_interest(
    principal: float,
    annual_rate: float,
    years: int,
    compounds_per_year: int
) -> float:
    """
    Calculate the final amount after compound interest is applied.

    Uses the standard compound interest formula:
        A = P * (1 + r/n)^(n*t)

    Args:
        principal (float): The initial amount of money (in dollars or any currency unit).
        annual_rate (float): The annual interest rate as a decimal (e.g., 0.05 for 5%).
        years (int): The number of years the money is invested or borrowed for.
        compounds_per_year (int): The number of times interest is compounded per year
                                   (e.g., 12 for monthly, 4 for quarterly, 1 for annually).

    Returns:
        float: The total amount after interest has been applied, rounded to 2 decimal places.

    Examples:
        >>> calculate_compound_interest(1000, 0.05, 10, 12)
        1647.01
        >>> calculate_compound_interest(5000, 0.03, 5, 1)
        5796.37
    """
    amount = principal * (1 + annual_rate / compounds_per_year) ** (compounds_per_year * years)
    return round(amount, 2)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------
import pytest


def test_basic_annual_compounding():
    """$1000 at 10% annually for 1 year should return $1100."""
    result = calculate_compound_interest(1000, 0.10, 1, 1)
    assert result == 1100.00


def test_monthly_compounding():
    """$1000 at 5% compounded monthly for 10 years — well-known result ~$1647.01."""
    result = calculate_compound_interest(1000, 0.05, 10, 12)
    assert result == 1647.01


def test_quarterly_compounding():
    """$5000 at 4% compounded quarterly for 3 years."""
    result = calculate_compound_interest(5000, 0.04, 3, 4)
    expected = round(5000 * (1 + 0.04 / 4) ** (4 * 3), 2)
    assert result == expected


def test_zero_interest_rate():
    """At 0% interest, the principal should remain unchanged regardless of compounding."""
    result = calculate_compound_interest(2500, 0.0, 5, 12)
    assert result == 2500.00


def test_single_compound_period():
    """One compounding period with known values."""
    result = calculate_compound_interest(10000, 0.06, 1, 1)
    assert result == 10600.00


def test_high_frequency_compounding():
    """Daily compounding (365 times/year) should approach continuous compounding."""
    result = calculate_compound_interest(1000, 0.05, 1, 365)
    # Continuous compounding would give e^0.05 * 1000 ≈ 1051.27
    assert 1051.00 <= result <= 1051.30
'''

BAD_CODE_DELIVERABLE = '''
def calculate_compound_interest(principal, annual_rate, years, compounds_per_year):
    amount = principal * (1 + annual_rate / compounds_per_year) ** (compounds_per_year * years)
    return round(amount, 2)
'''

# ---------------------------------------------------------------------------
# Test 1: Writing
# ---------------------------------------------------------------------------

async def test_writing():
    section("TEST 1: WRITING — Scope Parsing")

    t0 = time.time()
    scope = await run_scope_parsing(WRITING_DESCRIPTION, "writing")
    t1 = time.time()
    print(f"Scope parsing completed in {t1 - t0:.2f}s")
    print(f"Extracted {len(scope.criteria)} criteria, {len(scope.warnings)} warnings, revision_limit={scope.revision_limit}")
    for c in scope.criteria:
        print(f"  [{c.id}] {c.label} (measurable={c.measurable})")
        print(f"        {c.description}")
    if scope.warnings:
        print("Warnings:")
        for w in scope.warnings:
            print(f"  ! '{w.original_text}' — {w.issue}")
            print(f"    Suggestion: {w.suggestion}")

    # ---- Happy path ----
    subsection("TEST 1a: WRITING — Good Deliverable Evaluation")
    t2 = time.time()
    analyzer_out, verdict = await run_evaluation(
        GOOD_WRITING_DELIVERABLE, None, scope.criteria, "writing"
    )
    t3 = time.time()
    print(f"Evaluation completed in {t3 - t2:.2f}s")
    print(f"Verdict: {verdict.verdict} ({verdict.passed}/{verdict.total} passed)")
    print(f"Action: {verdict.action}")
    print(f"Summary: {verdict.summary}")
    if verdict.remediation:
        print(f"Remediation: {verdict.remediation}")
    print("\nPer-criterion results:")
    for e in analyzer_out.evaluations:
        icon = "PASS" if e.result == "PASS" else "FAIL"
        print(f"  [{icon}] {e.criterion_id} — {e.label} (confidence={e.confidence})")
        print(f"        {e.reasoning}")

    # ---- Bad path ----
    subsection("TEST 1b: WRITING — Bad Deliverable Evaluation")
    t4 = time.time()
    bad_analyzer_out, bad_verdict = await run_evaluation(
        BAD_WRITING_DELIVERABLE, None, scope.criteria, "writing"
    )
    t5 = time.time()
    print(f"Evaluation completed in {t5 - t4:.2f}s")
    print(f"Verdict: {bad_verdict.verdict} ({bad_verdict.passed}/{bad_verdict.total} passed)")
    print(f"Action: {bad_verdict.action}")
    print(f"Summary: {bad_verdict.summary}")
    if bad_verdict.remediation:
        print(f"Remediation: {bad_verdict.remediation}")
    print("\nPer-criterion results:")
    for e in bad_analyzer_out.evaluations:
        icon = "PASS" if e.result == "PASS" else "FAIL"
        print(f"  [{icon}] {e.criterion_id} — {e.label} (confidence={e.confidence})")
        print(f"        {e.reasoning}")

    # ---- Mediation on the bad deliverable ----
    subsection("TEST 1c: WRITING — Mediation (client disputes bad deliverable verdict)")
    client_argument = (
        "The freelancer delivered a 4-paragraph article that barely covers one of the three "
        "required topics. It contains no statistics, no structure, and is well under the "
        "minimum word count. This does not meet what we agreed to. I want a full refund."
    )
    freelancer_argument = (
        "I submitted a complete article covering solar energy cost savings, environmental "
        "benefits, and energy independence. The word count was shorter than specified but "
        "the content is high quality and captures all the key points. Writing concisely "
        "should be valued. I put in real work and deserve fair compensation."
    )
    t6 = time.time()
    mediation = await run_mediation(
        WRITING_DESCRIPTION,
        scope.criteria,
        BAD_WRITING_DELIVERABLE,
        bad_analyzer_out.evaluations,
        bad_verdict,
        client_argument,
        freelancer_argument
    )
    t7 = time.time()
    print(f"Mediation completed in {t7 - t6:.2f}s")
    print(f"Proposed split: Freelancer {mediation.proposed_split.freelancer_percentage}% / Client {mediation.proposed_split.client_refund_percentage}%")
    print(f"Reasoning: {mediation.reasoning}")
    print("\nCriterion breakdown:")
    for cb in mediation.criterion_breakdown:
        print(f"  [{cb.status}] {cb.id} (weight={cb.weight_percentage}%) — {cb.note}")

    return scope


# ---------------------------------------------------------------------------
# Test 2: Code
# ---------------------------------------------------------------------------

async def test_code():
    section("TEST 2: CODE — Scope Parsing")

    t0 = time.time()
    scope = await run_scope_parsing(CODE_DESCRIPTION, "code")
    t1 = time.time()
    print(f"Scope parsing completed in {t1 - t0:.2f}s")
    print(f"Extracted {len(scope.criteria)} criteria, {len(scope.warnings)} warnings, revision_limit={scope.revision_limit}")
    for c in scope.criteria:
        print(f"  [{c.id}] {c.label} (measurable={c.measurable})")
        print(f"        {c.description}")
    if scope.warnings:
        print("Warnings:")
        for w in scope.warnings:
            print(f"  ! '{w.original_text}' — {w.issue}")
            print(f"    Suggestion: {w.suggestion}")

    # ---- Happy path ----
    subsection("TEST 2a: CODE — Good Deliverable Evaluation")
    t2 = time.time()
    analyzer_out, verdict = await run_evaluation(
        GOOD_CODE_DELIVERABLE, None, scope.criteria, "code"
    )
    t3 = time.time()
    print(f"Evaluation completed in {t3 - t2:.2f}s")
    print(f"Verdict: {verdict.verdict} ({verdict.passed}/{verdict.total} passed)")
    print(f"Action: {verdict.action}")
    print(f"Summary: {verdict.summary}")
    if verdict.remediation:
        print(f"Remediation: {verdict.remediation}")
    print("\nPer-criterion results:")
    for e in analyzer_out.evaluations:
        icon = "PASS" if e.result == "PASS" else "FAIL"
        print(f"  [{icon}] {e.criterion_id} — {e.label} (confidence={e.confidence})")
        print(f"        {e.reasoning}")

    # ---- Bad path ----
    subsection("TEST 2b: CODE — Bad Deliverable Evaluation")
    t4 = time.time()
    bad_analyzer_out, bad_verdict = await run_evaluation(
        BAD_CODE_DELIVERABLE, None, scope.criteria, "code"
    )
    t5 = time.time()
    print(f"Evaluation completed in {t5 - t4:.2f}s")
    print(f"Verdict: {bad_verdict.verdict} ({bad_verdict.passed}/{bad_verdict.total} passed)")
    print(f"Action: {bad_verdict.action}")
    print(f"Summary: {bad_verdict.summary}")
    if bad_verdict.remediation:
        print(f"Remediation: {bad_verdict.remediation}")
    print("\nPer-criterion results:")
    for e in bad_analyzer_out.evaluations:
        icon = "PASS" if e.result == "PASS" else "FAIL"
        print(f"  [{icon}] {e.criterion_id} — {e.label} (confidence={e.confidence})")
        print(f"        {e.reasoning}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

async def main():
    total_start = time.time()
    print("\nLOCKSTEP AGENT PIPELINE — END-TO-END TEST")
    print(f"Started at: {time.strftime('%Y-%m-%d %H:%M:%S')}")

    await test_writing()
    await test_code()

    total_end = time.time()
    section(f"ALL TESTS COMPLETE — Total time: {total_end - total_start:.2f}s")


if __name__ == "__main__":
    asyncio.run(main())
